apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
  - name: "6003"
    port: 6003
    targetPort: 6003
  selector:
    service: backend-feed
