apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  ports:
  - name: "8100"
    port: 80
    targetPort: 80
  selector:
    service: frontend
#  type: LoadBalancer
